board/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name = "board"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("user/register/", views.RegisterView.as_view(), name="register"),
    path("user/login/", views.CustomLoginView.as_view(), name="login"),
    path("user/logout/", auth_view.LogoutView.as_view(), name="logout"),
    path("user/update/", views.CustomUserUpdateView.as_view(), name="user_update"),
    path("user/update/profile_image/", views.CustomUserUpdateProfileImgView.as_view(),
         name="user_update_profile_image"),
    path("user/delete/profile_image/", views.DeleteProfileImgView.as_view(), name="user_profile_image_delete"),

    path("post/create/", views.PostCreateView.as_view(), name="post_create"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path("post/update/<int:pk>/", views.PostUpdateView.as_view(), name="post_update"),
    path("post/delete/<int:pk>/", views.PostDeleteView.as_view(), name="post_delete"),
    path("post/like/<int:pk>/", views.PostLikeView.as_view(), name="post_like"),

    path("comment/create/<int:board_id>/", views.CommentCreateView.as_view(), name="comment_create"),
    path("comment/delete/<int:pk>/", views.CommentDeleteView.as_view(), name="comment_delete"),
]

community/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin7/', admin.site.urls),
    path("", include("board.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/models.py
import datetime
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone
from .managers import CustomUserManager
from django.core.validators import MinLengthValidator, RegexValidator

alphanumeric_validator = RegexValidator(
    regex=r'^[a-zA-Z0-9]+$',
    message='영어, 숫자 조합만 가능합니다.',
    code='invalid_alphanumeric'
)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    user_id = models.CharField(max_length=15, validators=[MinLengthValidator(3), alphanumeric_validator], unique=True)
    profile_image = models.ImageField(upload_to='profile_image', null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    USERNAME_FIELD = "user_id"

    objects = CustomUserManager()

    class Meta:
        db_table = 'users'
        verbose_name_plural = 'users'

    def __str__(self):
        return self.user_id


class Post(models.Model):
    title = models.CharField(max_length=50, validators=[MinLengthValidator(2)])
    content = models.TextField(max_length=1000, validators=[MinLengthValidator(2)])
    writer = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'posts'

    def __str__(self):
        return self.title

    def was_published_recently(self):
        return timezone.now() - datetime.timedelta(days=1) <= self.created_at

    def was_published_this_year(self):
        return self.created_at.year == timezone.now().year

    def count_post_like(self):
        return PostLike.objects.filter(post=self).count()

    def get_comment(self):
        return Comment.objects.filter(post=self, is_active=True).order_by('-created_at')


class PostLike(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'post_like'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    content = models.TextField(max_length=1000, validators=[MinLengthValidator(1)])
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'comments'

    def was_published_recently(self):
        return timezone.now() - datetime.timedelta(days=1) <= self.created_at

    def was_published_this_year(self):
        return self.created_at.year == timezone.now().year

board/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, UsernameField, \
    PasswordChangeForm
from django.forms import TextInput, ModelForm, Textarea

from .models import CustomUser, Post, Comment


class CustomUserCreationForm(UserCreationForm):
    profile_image = forms.ImageField(required=False,
                                     widget=forms.ClearableFileInput(
                                         attrs={'class': 'form-control', 'id': 'inputGroupFile02'})
                                     )
    password1 = forms.CharField(
        min_length=4,
        label='',
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "new-password",
                   'class': "form-control",
                   'id': 'floatingPassword'}),
        error_messages={
            'required': "필수 정보입니다.",
        }
    )
    password2 = None

    class Meta:
        model = CustomUser
        fields = ("user_id", "profile_image")
        widgets = {
            'user_id': TextInput(attrs={
                'class': "form-control", 'id': 'floatingInput'
            }),
        }
        error_messages = {
            'user_id': {
                'required': "필수 정보입니다.",
                'unique': "이미 등록된 아이디입니다. 다른 아이디를 입력해 주세요.",
                'max_length': "아이디는 15글자 이하만 가능합니다.",
                'min_length': "아이디는 3글자 이상만 가능합니다.",
            },
        }


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("user_id",)


class CustomUserLoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(
        attrs={"autofocus": True,
               'class': "form-control",
               'id': 'floatingInput'
               }))
    password = forms.CharField(
        min_length=4,
        label='',
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "new-password",
                   'class': "form-control",
                   'id': 'floatingPassword'}),
        error_messages={
            'required': "필수 정보입니다.",
        }
    )

    error_messages = {
        'invalid_login': '아이디 또는 비밀번호가 올바르지 않습니다. 다시 시도해 주세요.',
    }


class CustomUserUpdateForm(PasswordChangeForm):
    old_password = forms.CharField(
        min_length=4,
        label='',
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "new-password",
                   'class': "form-control",
                   'id': 'floatingPassword'}),
        error_messages={
            'required': "필수 정보입니다.",
        }
    )
    new_password1 = forms.CharField(
        min_length=4,
        label='',
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "new-password",
                   'class': "form-control",
                   'id': 'floatingPassword'}),
        error_messages={
            'required': "필수 정보입니다.",
        }
    )
    new_password2 = None


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]
        widgets = {
            'title': TextInput(attrs={
                'placeholder': '제목을 입력해주세요.',
                'class': 'form-control'
            }),
            'content': Textarea(attrs={
                'placeholder': '내용을 입력해주세요.',
                'class': 'form-control'
            })
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
        widgets = {
            'content': Textarea(attrs={
                'placeholder': '내용을 입력해주세요.',
                'class': 'form-control'
            })
        }

board/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views import generic, View
from django.contrib.auth.views import LoginView, PasswordChangeView
from .models import Post, PostLike, Comment
from .forms import CustomUserCreationForm, CustomUserLoginForm, PostForm, CustomUserUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexView(generic.ListView):
    template_name = 'board/index.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.filter(is_active=True).order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = context['posts']
        post_like_count_dict = {}

        for post in posts:
            post_like_count = PostLike.objects.filter(post=post).count()
            post_like_count_dict[post] = post_like_count
        context['post_like_count_dict'] = post_like_count_dict

        current_page_num = context['page_obj'].number
        total_page = context['paginator'].num_pages

        x, y = divmod(current_page_num, self.paginate_by)
        if y == 0:
            x -= 1

        start_page = x * self.paginate_by + 1
        last_page = min(total_page, start_page + self.paginate_by - 1)

        context['start_page'] = start_page
        context['last_page'] = last_page
        context['page_range'] = range(start_page, 1 + last_page)
        context['have_next_range'] = total_page > last_page

        return context


class RegisterView(generic.CreateView):
    template_name = 'board/register.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('board:login')

    def form_valid(self, form):
        user = form.save(commit=False)

        profile_image = self.request.FILES.get('profile_image')
        if profile_image:
            user.profile_image = profile_image
        user.save()

        return super().form_valid(form)


class CustomLoginView(LoginView):
    template_name = 'board/login.html'
    form_class = CustomUserLoginForm


class CustomUserUpdateView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'board/user_update.html'
    form_class = CustomUserUpdateForm
    success_url = reverse_lazy('board:index')


class CustomUserUpdateProfileImgView(LoginRequiredMixin, View):

    def get(self, request):
        template_name = 'board/user_update_profile_img.html'
        context = {"current_profile_image": request.user.profile_image}
        return render(request, template_name, context)

    def post(self, request):
        uploaded_image = request.FILES.get('profile_image')

        if uploaded_image:
            request.user.profile_image = uploaded_image
            request.user.save()
        return HttpResponseRedirect(reverse('board:index'))


class DeleteProfileImgView(LoginRequiredMixin, View):

    def post(self, request):
        request.user.profile_image = None
        request.user.save()
        return HttpResponseRedirect(reverse('board:index'))


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'board/post_create.html'
    form_class = PostForm
    success_url = reverse_lazy('board:index')

    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super().form_valid(form)


class PostDetailView(generic.DetailView):
    model = Post
    template_name = "board/post_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        post = context['post']
        context["post_like_count"] = post.count_post_like()

        user = self.request.user
        context["like_post"] = False

        if user.is_authenticated:
            like_post = PostLike.objects.filter(user=user, post=post).exists()
            if like_post:
                context["like_post"] = True

        context['comments'] = post.get_comment()
        return context


class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = "board/post_update.html"
    success_url = reverse_lazy('board:index')


class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Post

    success_url = reverse_lazy('board:index')


class PostLikeView(LoginRequiredMixin, View):

    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        user = request.user

        existing_like = PostLike.objects.filter(post=post, user=user)

        if not existing_like:
            PostLike.objects.create(post=post, user=user)
        else:
            existing_like.delete()

        return redirect('board:post_detail', pk=pk)


class CommentCreateView(LoginRequiredMixin, View):

    def post(self, request, board_id):
        comment_text = self.request.POST.get("comment_text")

        if comment_text:
            Comment.objects.create(
                content=comment_text,
                user=self.request.user,
                post=Post.objects.get(pk=board_id)
            )
        return redirect('board:post_detail', pk=board_id)


class CommentDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Comment

    def get_success_url(self):
        post = self.object.post
        return reverse('board:post_detail', kwargs={'pk': post.pk})

board/templates/board/comment_delete.html
<div class="modal fade" id="delete_comment_Modal" tabindex="-1" aria-labelledby="delete_comment_ModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
        <h1 class="modal-title fs-5" id="delete_comment_ModalLabel">주의</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
              <div class="modal-body">
                  <strong>정말로 댓글을 삭제하시겠습니까?</strong>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                  <form method="post" action="{% url 'board:comment_delete' comment.pk %}">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-danger">삭제</button>
                    </form>
              </div>
            </div>
          </div>
        </div>

board/templates/board/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container" style="max-width: 60vw;">
    <table class="table table-hover">
        <thead>
        <tr>
            <th class="col-1 text-center" scope="col">#</th>
            <th class="col-6 text-center" scope="col">제목</th>
            <th class="col-2 text-center" scope="col">글쓴이</th>
            <th class="col-5 text-center" scope="col">작성일</th>
            <th class="col-1 text-center" scope="col"><i class="fa-regular fa-thumbs-up fa-2x"></i></th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for post in posts %}
            <tr>
                <th class="text-center" scope="row">{{ page_obj.number | calculate_table_number:forloop.counter }}</th>
                <td class="text-center">
                    <a class="link-underline link-underline-opacity-0 link-underline-opacity-75-hover"
                       href="{% url 'board:post_detail' post.pk %}"
                       style="color: inherit;">{{ post.title|truncatechars:30 }}
                    </a>
                </td>
                <td class="text-center">
                    {% if post.writer.user_id is None %}
                     -
                    {% else %}
                        {% include "board/profile_img.html" %}
                        {{ post.writer.user_id }}
                    {% endif %}</td>

                    {% if post.was_published_recently %}
                        <td class="text-center">{{ post.created_at| timesince }} 전 </td>
                    {% elif post.was_published_this_year %}
                        <td class="text-center">{{ post.created_at|date:"m/d H:i" }}</td>
                    {% else %}
                        <td class="text-center">{{ post.created_at|date:"Y/m/d H:i" }}</td>
                    {% endif %}

                <td>{{ post_like_count_dict | get_value:post }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
      {% if start_page > 1 %}
        <li class="page-item">
          <a class="page-link" href="?page={{ start_page|add:'-1' }}">이전</a>
        </li>
      {% endif %}
    {% for page in page_range %}
      {% if page == page_obj.number %}
      <li class="page-item active" aria-current="page">
          <span class="page-link">{{ page }}</span>
      </li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page }}">{{page}}</a></li>
      {% endif %}
    {% endfor %}
      {% if have_next_range %}
    <li class="page-item">
      <a class="page-link" href="?page={{ last_page|add:'1' }}">다음</a>
    </li>
      {% endif %}
  </ul>
</nav>
        <button type="button" class="btn btn-primary float-end" onclick="window.location.href = '{% url 'board:post_create' %}';">글쓰기</button>
</div>
{% endblock %}

board/templates/board/login.html
{% extends 'base.html' %}
  {% block content %}
<div class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <div class="col-md-3">
        <form action="{% url 'board:login' %}" method="post">
            {% csrf_token %}
            <div class="form-floating mb-3">
                {{ form.username }}
                {{ form.username.errors }}
                <label for="floatingInput">아이디</label>
            </div>
            <div class="form-floating mb-3">
                {{ form.password }}
                {{ form.password.errors }}

                <label for="floatingPassword">비밀번호</label>
            </div>
            <button class="btn btn-primary w-100 py-2" type="submit">로그인</button>
        </form>
    </div>
</div>
{% endblock %}

board/templates/board/post_create.html
{% extends 'base.html' %}
{% block content %}

<div class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <form action="{% url 'board:post_create' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3">
            {{ field }}
        </div>
        {% endfor %}
        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary" style="margin-right: 10px;">저장</button>
            <button type="submit" class="btn btn-secondary">취소</button>
        </div>
    </form>
</div>
{% endblock %}

board/templates/board/post_delete.html
<div class="modal fade" id="delete_post_Modal" tabindex="-1" aria-labelledby="delete_post_ModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
        <h1 class="modal-title fs-5" id="delete_post_ModalLabel">주의</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
              <div class="modal-body">
                  <strong>정말로 게시글을 삭제하시겠습니까?</strong>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                  <form method="post" action="{% url 'board:post_delete' post.pk %}">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-danger">삭제</button>
                    </form>
              </div>
            </div>
          </div>
        </div>

board/templates/board/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-1">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center">{{ post.title }}</h1>
            {% if post.writer.user_id is None %}
                <p class="text-end mb-2">-</p>
            {% else %}
                <div class="d-flex align-items-center justify-content-end">
                    {% include "board/profile_img.html" %}
                    <strong>{{ post.writer.user_id }}</strong>
                </div>
            {% endif %}
                <p class="text-end mb-2">{{ post.created_at|date:"Y/m/d H:i" }}</p>
            {% if user.is_authenticated and user == post.writer %}
            <div class="d-flex justify-content-end">
                <a class="mx-3" href="{% url 'board:post_update' post.pk %}"><i class="fa fa-edit text-success fa-lg"></i></a>
                <a href="" data-bs-toggle="modal" data-bs-target="#delete_post_Modal"> <i class="fa fa-trash text-danger fa-lg"></i></a>
                <!-- delete modal -->
                 {% include 'board/post_delete.html' %}
            </div>
            {% endif %}
            {% if user.is_authenticated and user != post.writer %}
            <div class="d-flex justify-content-end">
                {% if like_post %}
                <a href="{% url 'board:post_like' post.pk %}">
                    <i class="fa-regular fa-thumbs-down fa-1x"></i>
                </a>
                {% else %}
                <a href="{% url 'board:post_like' post.pk %}">
                    <i class="fa-regular fa-thumbs-up fa-1x"></i>
                </a>
                {% endif %}
                <strong style="margin-left: 5px;"> 좋아요 {{ post_like_count }}</strong>
            </div>
            {% endif %}
            <hr>

            <p>{{ post.content }}</p>
        </div>
    </div>

<div class="row justify-content-center mt-5">
    <div class="col-md-6">
        <hr>
        {% for comment in comments %}
            <div class="mb-3">
                <div class="d-flex justify-content-between">
                    <div>
                        {% if comment.user.profile_image %}
                             <img src="{{ comment.user.profile_image.url }}" class="img-thumbnail img-circle-small" alt="프로필 이미지">
                        {% else %}
                             <img src="{% static 'default.jpg' %}" class="img-thumbnail img-circle-small" alt="기본 이미지">
                        {% endif %}
                        <strong>{{ comment.user.user_id }}</strong>
                    </div>
                    <small>
                        {% if comment.was_published_recently %}
                            {{ comment.created_at| timesince }} 전
                        {% elif comment.was_published_this_year %}
                            {{ comment.created_at|date:"m/d H:i" }}
                        {% else %}
                            {{ comment.created_at|date:"Y/m/d H:i" }}
                        {% endif %}
                    </small>
                </div>
                <div class="d-flex justify-content-between mt-3">
                <p>{{ comment.content }}</p>
                {% if user.is_authenticated and user == comment.user %}
                    <div>
                    <a href="" data-bs-toggle="modal" data-bs-target="#delete_comment_Modal">
                        <i class="fa fa-trash text-danger fa-lg"></i>
                    </a>
                    </div>
                    {% include 'board/comment_delete.html' %}
                {% endif %}
                </div>
            </div>
                <hr>
        {% endfor %}

        <form action="{% url 'board:comment_create' post.pk %}" method="post">
            {% csrf_token %}
            <textarea name="comment_text" class="form-control mb-2" placeholder="댓글을 입력하세요"></textarea>
            <button class="btn btn-primary float-end">댓글 등록</button>
        </form>
    </div>
</div>
</div>

{% endblock %}

board/templates/board/post_update.html
{% extends 'base.html' %}
{% block content %}

<div class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <form action="{% url 'board:post_update' post.pk %}" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3">
            {{ field }}
        </div>
        {% endfor %}
        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary" style="margin-right: 10px;">수정</button>
            <button type="submit" class="btn btn-secondary">취소</button>
        </div>
    </form>
</div>
{% endblock %}

board/templates/board/profile_img.html
{% load static %}
{% if post.writer.profile_image %}
    <img src="{{ post.writer.profile_image.url }}" class="img-circle-small" alt="프로필 이미지">
{% else %}
    <img src="{% static 'default.jpg' %}" class="img-thumbnail img-circle-small" alt="기본 이미지">
{% endif %}

board/templates/board/profile_img_delete.html
<div class="modal fade" id="delete_profile_image_Modal" tabindex="-1" aria-labelledby="delete_profile_image_ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="delete_profile_image_ModalLabel">주의</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
              <strong>정말로 프로필 이미지를 삭제하시겠습니까?</strong>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
          <form method="post" action="{% url 'board:user_profile_image_delete' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">삭제</button>
          </form>
      </div>
    </div>
  </div>
</div>

board/templates/board/register.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <div class="col-md-3">
        <form action="{% url 'board:register' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-floating mb-3">
                {{ form.user_id }}
                {{ form.user_id.errors }}
                <label for="floatingInput">아이디</label>
            </div>
            <div class="form-floating mb-3">
                {{ form.password1 }}
                {{ form.password1.errors }}
                <label for="floatingPassword">비밀번호</label>
            </div>
            <hr>
            <p>프로필 사진 설정 <strong>(선택)</strong></p>
            <div class="input-group mb-3">
                  {{ form.profile_image }}
                  {{ form.profile_image.errors }}
            </div>
            <button class="btn btn-primary w-100 py-2" type="submit">회원가입</button>
        </form>
    </div>
</div>
{% endblock %}

board/templates/board/user_update.html
{% extends 'base.html' %}
  {% block content %}
<div class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <div class="col-md-3">
        <form action="{% url 'board:user_update' %}" method="post">
            {% csrf_token %}
            <div class="form-floating mb-3">
                {{ form.old_password }}
                {{ form.old_password.errors }}
                <label for="floatingInput">기존 비밀번호</label>
            </div>

            <div class="form-floating mb-3">
                {{ form.new_password1 }}
                {{ form.new_password1.errors }}
                <label for="floatingPassword">새 비밀번호</label>
            </div>

            <button class="btn btn-primary w-100 py-2" type="submit">변경하기</button>
        </form>
    </div>
</div>
{% endblock %}

board/templates/board/user_update_profile_img.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <div class="col-md-3">
        {% if user.profile_image %}
        <div class="d-flex align-items-end justify-content-between mb-4">
    <h6 class="me-3 mb-0">기존 프로필</h6>
    <div class="d-flex align-items-end">
        <img src="{{ user.profile_image.url }}" class="img-thumbnail img-circle me-3" alt="프로필 이미지" >
        <a href="" data-bs-toggle="modal" data-bs-target="#delete_profile_image_Modal" class="text-danger me-3">
            <i class="fa fa-trash fa-lg"></i>
        </a>
    </div>
</div>
        {% include 'board/profile_img_delete.html' %}
        <hr>
        {% endif %}

     <form action="{% url 'board:user_update_profile_image' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="d-flex align-items-center">
            <input type="file" name="profile_image" accept="image/*" id="id_profile_image" onchange="previewImage(this);" style="margin-right: 10px;">
            <img class="img-thumbnail img-circle" id="preview" src="#" alt="미리보기 이미지" style="display: none;">
        </div>
        <button class="btn btn-primary w-100 py-2 mt-4" type="submit">프로필 사진 변경</button>
     </form>

        <script>
            function previewImage(input) {
                var preview = document.getElementById('preview');
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        preview.src = e.target.result;
                        preview.style.display = 'block';
                    };
                    reader.readAsDataURL(input.files[0]);
                } else {
                    preview.src = '#';
                    preview.style.display = 'none';
                }
            }
        </script>
    </div>
</div>
{% endblock %}