board/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name = "board"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("user/register/", views.RegisterView.as_view(), name="register"),
    path("user/login/", views.CustomLoginView.as_view(), name="login"),
    path("user/logout/", auth_view.LogoutView.as_view(), name="logout"),
    path("user/update/", views.CustomUserUpdateView.as_view(), name="user_update"),
    path("user/update/profile_image/", views.CustomUserUpdateProfileImgView.as_view(),
         name="user_update_profile_image"),
    path("user/delete/profile_image/", views.DeleteProfileImgView.as_view(), name="user_profile_image_delete"),

    path("post/create/", views.PostCreateView.as_view(), name="post_create"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path("post/update/<int:pk>/", views.PostUpdateView.as_view(), name="post_update"),
    path("post/delete/<int:pk>/", views.PostDeleteView.as_view(), name="post_delete"),
    path("post/like/<int:pk>/", views.PostLikeView.as_view(), name="post_like"),

    path("comment/create/<int:board_id>/", views.CommentCreateView.as_view(), name="comment_create"),
    path("comment/delete/<int:pk>/", views.CommentDeleteView.as_view(), name="comment_delete"),
]

community/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin7/', admin.site.urls),
    path("", include("board.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
   <script src="https://kit.fontawesome.com/c3fd66b01d.js" crossorigin="anonymous"></script>
    <link href="{% static 'board/css/style.css' %}" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</head>
    <body>
        {% include 'header.html' %}
        {% block content %} {% endblock %}
    </body>
</html>

templates/header.html
{% load static %}
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-2 mb-3 border-bottom" style="margin-right: 20px">
      <div class="col-md-3 mb-2 mb-md-0">
        <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
          <svg class="bi" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>
      </div>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
          {% if user.is_authenticated %}
          <li><a href="{% url 'board:index' %}" class="nav-link px-2 link-secondary">
          <i class="fa-solid fa-house-user fa-2x"></i>
        </a></li>
          {% else %}
          <li><a href="{% url 'board:index' %}" class="nav-link px-2 link-secondary">
              <i class="fa-solid fa-house fa-2x" ></i>
        </a></li>
          {% endif %}
      </ul>

      <div class="col-md-3 d-flex justify-content-end align-items-center">
          {% if user.is_authenticated %}
            {% if user.profile_image %}
                <img src="{{ user.profile_image.url }}" class="img-thumbnail img-circle me-2" alt="프로필 이미지">
            {% else %}
                <img src="{% static 'default.jpg' %}" class="img-thumbnail img-circle me-2" alt="기본 이미지">
            {% endif %}
              <div class="dropdown me-4">
                <a class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> <strong>{{user.user_id}}님</strong> </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'board:user_update' %}">비밀번호 변경</a></li>
                    <li><a class="dropdown-item" href="{% url 'board:user_update_profile_image' %}">프로필 사진 변경</a></li>
                  </ul>
              </div>
              <button type="button" class="btn btn-primary me-2" onclick="window.location.href = '{% url 'board:logout' %}';">로그아웃</button>
          {% else %}
        <button type="button" class="btn btn-outline-primary me-2" onclick="window.location.href = '{% url 'board:login' %}';">로그인</button>
        <button type="button" class="btn btn-primary" onclick="window.location.href = '{% url 'board:register' %}';">회원가입</button>
          {% endif %}
      </div>
    </header>